# Generated by Django 3.2.5 on 2021-08-15 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('topic_model', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detectedtopics',
            old_name='prediction_index',
            new_name='topic_index',
        ),
        migrations.AddField(
            model_name='detectedtopics',
            name='topic_name',
            field=models.CharField(default='Topic Name', max_length=50),
        ),
    ]
