# Generated by Django 3.2.5 on 2021-08-15 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_model', '0002_auto_20210815_0603'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topickeyword',
            old_name='predicted_keyword',
            new_name='topic_keyword',
        ),
    ]
